services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080/udp"
    networks:
      sensor-net:
        ipv4_address: 172.20.0.10


  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    networks:
      sensor-net:
        ipv4_address: 172.20.0.11
    command: ["--ip", "172.20.0.10", "--port", "8080", "-s", "9999999999999999"]

networks:
  sensor-net:
    name: sensor-net
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16


