services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080/udp"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    command: ["--ip", "server", "--port", "8080", "-s", "999999"]